"""
Vertex AI Gemini-powered complaint narrative generator.

Uses Gemini 2.0 Flash via Vertex AI (google.genai SDK).
Auth: Application Default Credentials — run `gcloud auth application-default login` locally.
On Cloud Run, the service account needs roles/aiplatform.user.

Returns "" on any failure so reports.py always falls back to the template safely.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def generate_complaint_narrative(
    carrier: str,
    zip_code: str,
    ghost_rate: float,
    rag_hits: list[dict],
    gcp_project: str | None,
    vertex_location: str = "us-central1",
) -> str:
    """
    Returns a 2-3 paragraph factual complaint narrative, or "" on failure/missing project.
    """
    if not gcp_project:
        return ""

    try:
        from google import genai  # type: ignore[import-untyped]

        client = genai.Client(vertexai=True, project=gcp_project, location=vertex_location)

        rag_context = "\n".join(
            f"- [{h.get('source', '')}]: {str(h.get('excerpt', ''))[:250]}"
            for h in (rag_hits or [])[:4]
        )

        prompt = f"""You are helping a patient document a health insurance network adequacy problem for a formal complaint.

Audit findings:
- Insurance carrier: {carrier}
- Member ZIP code: {zip_code}
- Ghost rate observed: {ghost_rate:.0%} of listed behavioral-health providers were unreachable or reported being out-of-network
- AI-voice verification calls were placed to each listed provider asking whether the practice accepts {carrier} for behavioral health and is accepting new patients

Regulatory context retrieved from official sources:
{rag_context if rag_context else "(no regulatory excerpts available)"}

Write exactly 2-3 factual paragraphs suitable for inclusion in a complaint letter to the NY Department of Financial Services (DFS) or the relevant state insurance regulator.
- Be factual and specific; cite the ghost rate and method
- Reference the regulatory frameworks above where relevant (e.g., MHPAEA network composition, NY ISC directory accuracy requirements)
- Do NOT give legal advice; do NOT recommend specific legal action
- Keep language professional and neutral

End your response with this exact disclaimer on a new line:
DISCLAIMER: This narrative was generated by an automated audit tool and is not legal advice. Review and edit carefully, and consult a licensed attorney before filing any formal complaint."""

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
        )
        text = (response.text or "").strip()
        return text if text else ""

    except Exception as exc:
        logger.warning("Vertex AI complaint narrative failed: %s", exc)
        return ""
